(ns shipping.ups.ups-units)

(def ups_units
  "From a PDF file slightly cleaned and then formatted.
  (ex: sed 's/\([A-Z\w]*\) = \([a-zA-Z]*\)/"\2" "\1"/' ups-units.txt)"
  { "Barrel" "BA"
    "Bundle" "BE"
    "Bag" "BG"
    "Bunch" "BH"
    "Box" "BOX"
    "Bolt" "BT"
    "Butt" "BU"
    "Canister" "CI"
    "Centimeter" "CM"
    "Container" "CON"
    "Crate" "CR"
    "Case" "CS"
    "Carton" "CT"
    "Cylinder" "CY"
    "Dozen" "DOZ"
    "Each" "EA"
    "Envelope" "EN"
    "Feet" "FT"
    "Kilogram" "KG"
    "Kilograms" "KGS"
    "Pound" "LB"
    "Pounds" "LBS"
    "Liter" "L"
    "Meter" "M"
    "Number" "NMB"
    "Packet" "PA"
    "Pallet" "PAL"
    "Piece" "PC"
    "Pieces" "PCS"
    "Proof Liters" "PF"
    "Package" "PKG"
    "Pair" "PR"
    "Pairs" "PRS"
    "Roll" "RL"
    "Set" "SET"
    "Square Meters" "SME"
    "Square Yards" "SYD"
    "Tube" "TU"
    "Yard" "YD"
    "Other" "OTH"} )